# Builder-side nix.conf (branch nix). Both experimental features on.
experimental-features = nix-command flakes serve-build-logs build-coordinator
sandbox = false
build-users-group =
substituters =
trusted-public-keys =
max-jobs = 4
keep-build-log = true
